var a1 = true && true;
print(a1);
var a2 = true && false;
print(a2);
var a3 = false && true;
print(a3);
var a4 = false && 3 == 4;
print(a4);
var a5 = "Gato" && "Cão";
print(a5);
var a6 = false && "Gato";
print(a6);
var a7 = "Gato" && false;
print(a7);

var b1 = true || true;
print(b1);
var b2 = true || false;
print(b2);
var b3 = false || true;
print(b3);
var b4 = false || 3 == 4;
print(b4);
var b5 = "Gato" || "Cão";
print(b5);
var b6 = false || "Gato";
print(b6);
var b7 = "Gato" || false;
print(b7);
